import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Header from "../header/header";
import Footer from "../footer/footer";
const inter = Inter({ subsets: ["latin"] });


const RootLayout = props => (
    <div>

        <Head>
            <title>My_Meteo App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />


        <main className={`${styles.main} ${inter.className}`}>

            {props.children}

        </main >

        <Footer />

    </div>
)

export default RootLayout;

