import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import Router from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }: any) {

  const handleSubmit = (e: any) => {

    e.preventDefault()
    const formData = new FormData(e.currentTarget);

    const lat = formData.get("lat")

    const lng = formData.get("lng")

    Router.push(`/?lat=${lat}&lng=${lng}`)

  }

  return (
    <>
      <Head>
        <title>My_Meteo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Insert your coordinates
          </p>
          <div style={{ display: "flex", textAlign: "center", justifyContent: "center" }}>

            <form onSubmit={handleSubmit}>

              <input type="text" name="lat" placeholder="Latitude" />
              <input type="text" name="lng" placeholder="Longitude" />
              <button type="submit">Search</button>

            </form>
          </div>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/Logo_Reply.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={120}
                height={40}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <div className={styles.description}>
            Elevation: {data.elevation}
          </div>

        </div>

        <div className={styles.grid}>



        </div>
      </main>
    </>
  );
}

// This gets called on every request
export async function getServerSideProps({ query }: any) {

  console.log("query:", query)

  // Fetch data from external API
  const res = await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${query.lat}&longitude=${query.lng}`)
  const data = await res.json()

  console.log("data:", data)


  // Pass data to the page via props
  return { props: { data } }
}
