import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });


const RootLayout = props => (
    <div>

        <Head>
            <title>My_Meteo App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="header">

            <h2>My header</h2>

        </div>

        <main className={`${styles.main} ${inter.className}`}>

            {props.children}

        </main >

        <div className="footer">
            <h2>My footer</h2>


        </div>

    </div>
)

export default RootLayout;

